# Generated by Django 5.0.12 on 2025-02-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
