# Generated by Django 5.0.12 on 2025-02-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_alter_element_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='element_images/'),
        ),
    ]
